### ISSUE TITLE
shorten tab names?

### ISSUE THREAD

**Issue by jovo** [neurodata/Matrix-Explorer#15]
what do you think about shortening tab names?
in particular, they don't all fit on a row for me.
i propose:
- upload
- heatmap
- sample summary
- feature summary
- outliers
- correlation
- embedding & clustering

**Comment by ikuznet1** [comment]
Agreed

**Comment by ikuznet1** [comment]
Done

**Comment by jovo** [comment]
cool - fyi - i'm at nyu and i'm gonna demo your stuff, so if you roll the
site, i can demo the newest stuff :)

On Fri, Jan 29, 2016 at 12:42 AM, ikuznet1 notifications@github.com wrote:

> Closed #15 https://github.com/openconnectome/Vector-Explorer/issues/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Vector-Explorer/issues/15#event-530840935
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by ikuznet1** [comment]
I rolled it. Seems stable.
