### ISSUE TITLE
in docs, link to some example csv files

### ISSUE THREAD

**Issue by jovo** [neurodata/Matrix-Explorer#17]
alternately, enable loading from url, and in docs, provide url of some example csv files.
note that we can store them at http://openconnecto.me/data/public/

**Comment by ikuznet1** [comment]
Any specific datasets, or should I use the built in r sets?

**Comment by jovo** [comment]
built-in are fine. or one's already with a public url

**Comment by jovo** [comment]
it would be great to link to the iris data, for example, right from the home page

**Comment by ikuznet1** [comment]
Seems stable now
