### ISSUE TITLE
Add ability to condition on data column (e.g., class labels)

### ISSUE THREAD

**Issue by wrgr** [neurodata/Matrix-Explorer#2]
For example, can we plot marginal distributions conditioned on class labels (i.e., grouped by an arbitrary column)

it might look like this:
https://chrisjmccormick.files.wordpress.com/2014/08/1d_example.png

**Comment by ikuznet1** [comment]
Done

**Comment by jovo** [comment]
wait, really, you did it? @ikuznet1 
i thought you said it was really hard?

**Comment by ikuznet1** [comment]
Yah, it was really tedious. Took a good nights rest to get it to work. I haven't made it so it displays the mean and median of the classes, but ill worry about that later. @jovo

**Comment by jovo** [comment]
cool!
