### ISSUE TITLE
mean & median don't work on some data

### ISSUE THREAD

**Issue by jovo** [neurodata/Matrix-Explorer#21]
[iris.txt](https://github.com/neurodata/Vector-Explorer/files/127268/iris.txt)

**Comment by ikuznet1** [comment]
I think this is fixed, although I am having a hard time recreating.

**Comment by ikuznet1** [comment]
Rebroke it :(
A big part of it has to do that I assume that class defining columns will contain strings.

**Comment by ikuznet1** [comment]
Resolved
